title: EthereumJS
description: Your Javascript Gateway to Ethereum
repository: ethereumjs
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

sass:
  load_paths:
    - assets/css                        # original sass


